.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "SPEC4PHP" "1" "March 2011" "Ivan -DrSlump- Montes" "Spec for PHP "
.
.SH "NAME"
\fBspec4php\fR \- cli runner
.
.SH "SYNOPSIS"
.
.nf

spec4php <FILE>
spec4php <DIRECTORY>
.
.fi
.
.SH "DESCRIPTION"
\fBSpec4php\fR runs the specified spec files and reports the results in the terminal\. For information on how to create spec files please refer to spec4php(7)\.
.
.SH "SPEC FILES"
The \fBspec4php\fR command expects input files to contain PHP code with \fBdescribe\fR and \fBit\fR blocks in it\.
.
.P
Giving a file path as argument, \fBspec4php\fR runs the tests contained in it
.
.SH "OPTIONS"
.
.SH "EXAMPLES"
.
.SH "BUGS"
.
.SH "COPYRIGHT"
Spec for PHP is Copyright (C) 2011 Ivan \-DrSlump\- Montes \fIhttp://pollinimini\.net\fR
.
.SH "SEE ALSO"
spec4php(3), spec4php(5), \fIhttp://github\.com/drslump/spec\-php\fR
